(function(){
  const $ = id => document.getElementById(id);
  const fmt = n => { try { return Number(n||0).toLocaleString('zh-Hant'); } catch(e){ return String(n??''); } };
  const fmtBig = b => { try { return BigInt(b).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ','); } catch(e){ return String(b??''); } };
  const num = (id,d=0)=>{ const v=Number($(id)?.value ?? d); return Number.isFinite(v)?v:d; };
  const STAR_COST_TABLE = Array.from({length:20}, (_,s)=>15 + s*10);
  function starCost(cur, tar){ cur=Math.max(0,Math.min(20,Math.floor(Number(cur)||0))); tar=Math.max(0,Math.min(20,Math.floor(Number(tar)||0))); if(tar<=cur)return 0; let total=0; for(let s=cur;s<tar;s++) total += STAR_COST_TABLE[s]||0; return total; }
  function auraCost(cur, tar){ cur=Math.max(1,Math.floor(Number(cur)||1)); tar=Math.max(cur,Math.floor(Number(tar)||cur)); let total=0; for(let lv=cur+1; lv<tar; lv++) total += lv*12; return total; }
  function starOptions(selected=20){ return Array.from({length:21},(_,i)=>`<option value="${i}" ${i===selected?'selected':''}>${i} 星</option>`).join(''); }
  function renderStarAuraPage(){ const r=$('reader'); if(!r)return; r.innerHTML=`<section class="card"><h1>降神、經驗、修練試算</h1><h2>星等 / 靈氣計算</h2><div class="calcTabs"><button class="calcTab active" type="button" data-star-tab="star">星等計算</button><button class="calcTab" type="button" data-star-tab="aura">靈氣計算</button></div><div id="starTabNeed"><h3>星等：需要的降神數量</h3><div class="kvGrid"><div class="kv"><div class="k">目前星等</div><div class="v"><select id="needCur">${starOptions(0)}</select></div></div><div class="kv"><div class="k">目標星等</div><div class="v"><select id="needTar">${starOptions(20)}</select></div></div><div class="kv"><div class="k">已有降神數量</div><div class="v"><input id="needOwned" type="number" value="0"></div></div><div class="kv"><div class="k">倍率</div><div class="v"><input id="needRate" type="number" value="1" step="0.1"></div></div></div><div class="quick"><button id="calcNeeds" type="button">計算星等<small>使用逐星需求表累加</small></button></div><div id="starNeedResult"></div></div><div id="starTabAura" style="display:none"><h3>靈氣：所需靈氣</h3><div class="kvGrid"><div class="kv"><div class="k">目前等級</div><div class="v"><input id="auraCur" type="number" value="1"></div></div><div class="kv"><div class="k">目標等級</div><div class="v"><input id="auraTar" type="number" value="20"></div></div></div><div class="quick"><button id="calcStarAura" type="button">計算靈氣<small>使用逐級需求表累加</small></button></div><div id="auraNeedResult"></div></div></section>`; }
  const oldSetJiang = window.setJiang;
  window.setJiang = function(kind){ if(kind==='starAura'){ renderStarAuraPage(); if(typeof closeDrawer==='function')closeDrawer(); window.scrollTo({top:0,behavior:'smooth'}); return; } if(typeof oldSetJiang==='function') return oldSetJiang(kind); };
  window.calcNeeds = function(){ const cur=Math.max(0,Math.min(20,Math.floor(num('needCur',0)))); const tar=Math.max(0,Math.min(20,Math.floor(num('needTar',20)))); const owned=Math.max(0,Math.floor(num('needOwned',0))); const rate=Math.max(0.0001,num('needRate',1)); const raw=starCost(cur,tar); const afterOwned=Math.max(0,raw-owned); const need=Math.ceil(afterOwned/rate); const box=$('starNeedResult'); if(box)box.innerHTML=`<div class="kvGrid" style="margin-top:12px"><div class="kv"><div class="k">星等區間</div><div class="v">${cur} 星 → ${tar} 星</div></div><div class="kv"><div class="k">原始需求</div><div class="v">${fmt(raw)} 顆降神</div></div><div class="kv"><div class="k">扣除已有</div><div class="v">${fmt(afterOwned)} 顆</div></div><div class="kv"><div class="k">倍率後還需</div><div class="v">${fmt(need)} 顆</div></div></div>`; };
  window.calcStarAura = function(){ const cur=Math.max(1,Math.floor(num('auraCur',1))); const tar=Math.max(cur,Math.floor(num('auraTar',cur))); const total=auraCost(cur,tar); const box=$('auraNeedResult'); if(box)box.innerHTML=`<div class="kvGrid" style="margin-top:12px"><div class="kv"><div class="k">等級區間</div><div class="v">${cur} → ${tar}</div></div><div class="kv"><div class="k">預估靈氣</div><div class="v">${fmt(total)}</div></div></div>`; };
})();
