#include status.ini
//
// 狀態資料
//

[DEFINE]

[STATUS]
ID = 1
Group = 1
Order = 3
Name = 麻痺
Param1 = -30
Param2 = 1

[STATUS]
ID = 62
Group = 1
Order = 5
Name = 大麻痺
Param1 = -30
Param2 = 1

[STATUS]
ID = 2
Group = 1
Order = 4
Name = 定身
Param1 = -60

[STATUS]
ID = 3
Group = 1
Order = 1
Name = 疾行
Param1 = 10
Param2 = 5

[STATUS]
ID = 46
Group = 1
Order = 1
Name = 海底疾行
Param1 = 10
Param2 = 5

[STATUS]
ID = 4
Group = 2
Order = 4
Name = 毒素
Param1 = 5
Param2 = -1

[STATUS]
ID = 5
Group = 2
Order = 5
Name = 烈毒
Param1 = 5
Param2 = -2

[STATUS]
ID = 6
Group = 2
Order = 6
Name = 劇毒
Param1 = 5
Param2 = -3

[STATUS]
ID = 7
Group = 2
Order = 7
Name = 蠱毒
Param1 = 5
Param2 = -4

[STATUS]
ID = 37
Group = 2
Order = 8
Name = 萬蠱毒
Param1 = 5
Param2 = -5

[STATUS]
ID = 55
Group = 2
Order = 9
Name = 龍女降蠱
Param1 = 5
Param2 = -6

[STATUS]
ID = 8
Group = 3
Order = 1
Name = 癒傷
Param1 = 10
Param2 = 1

[STATUS]
ID = 9
Group = 3
Order = 2
Name = 自療
Param1 = 10
Param2 = 3

[STATUS]
ID = 10
Group = 3
Order = 4
Name = 再生
Param1 = 10
Param2 = 5

[STATUS]
ID = 51
Group = 3
Order = 4
Name = 快速再生
Param1 = 10
Param2 = 8

[STATUS]
ID = 57
Group = 3
Order = 5
Name = 超快速再生
Param1 = 3
Param2 = 5

[STATUS]
ID = 117
Group = 3
Order = 5
Name = 極快速再生
Param1 = 3
Param2 = 10

[STATUS]
ID = 44
Group = 3
Order = 6
Name = 高速再生
Param1 = 3
Param2 = 20

[STATUS]
ID = 11
Group = 7
Order = 1
Name = 癒傷
Param1 = 10
Param2 = 1

[STATUS]
ID = 29
Group = 7
Order = 2
Name = 自療
Param1 = 10
Param2 = 2

[STATUS]
ID = 56
Group = 7
Order = 3
Name = 新手玉珮
Param1 = 10
Param2 = 3

[STATUS]
ID = 28
Group = 4
Order = 1
Name = 基本回精
Param1 = 10
Param2 = 1

[STATUS]
ID = 13
Group = 4
Order = 2
Name = 回精
Param1 = 10
Param2 = 3

[STATUS]
ID = 14
Group = 4
Order = 3
Name = 快速回精
Param1 = 10
Param2 = 5

[STATUS]
ID = 58
Group = 4
Order = 4
Name = 超快速回精
Param1 = 3
Param2 = 8

[STATUS]
ID = 111
Group = 4
Order = 5
Name = 極快速回精
Param1 = 3
Param2 = 10

[STATUS]
ID = 123
Group = 4
Order = 6
Name = 高速回精
Param1 = 3
Param2 = 15

[STATUS]
ID = 45
Group = 4
Order = 5
Name = 基本吸精
Param1 = 1
Param2 = -15

[STATUS]
ID = 12
Group = 15
Order = 1
Name = 吸血
Param1 = -98

[STATUS]
ID = 41
Group = 15
Order = 2
Name = 大吸血
Param1 = -90

[STATUS]
ID = 15
Group = 6
Order = 2
Name = 勇猛
Param1 = 60
Param2 = 40

[STATUS]
ID = 42
Group = 6
Order = 1
Name = 小勇猛
Param1 = 30
Param2 = 20

[STATUS]
ID = 48
Group = 6
Order = 2
Name = 狂暴
Param1 = 50
Param2 = 30

[STATUS]
ID = 49
Group = 6
Order = 2
Name = 防禦
Param1 = -20
Param2 = -30

[STATUS]
ID = 61
Group = 6
Order = 2
Name = 防禦II
Param1 = -30
Param2 = -50

[STATUS]
ID = 16
Group = 5
Order = 2
Name = 鐵皮
Param1 = -30

[STATUS]
ID = 39
Group = 5
Order = 1
Name = 鐵皮
Param1 = -20

[STATUS]
ID = 59
Group = 5
Order = 1
Name = 鐵皮
Param1 = -10

[STATUS]
ID = 17
Group = 5
Order = 2
Name = 避邪
Param2 = -30

[STATUS]
ID = 40
Group = 5
Order = 1
Name = 避邪
Param2 = -20

[STATUS]
ID = 60
Group = 24
Order = 1
Name = 敏銳
Param1 = 15

[STATUS]
ID = 18
Group = 8
Order = 1
Name = 敏銳
Param1 = 40

[STATUS]
ID = 19
Group = 8
Order = 2
Name = 盲目
Param1 = -40

[STATUS]
ID = 63
Group = 8
Order = 3
Name = 大盲目
Param1 = -40

[STATUS]
ID = 36
Group = 20
Order = 1
Name = 敏銳
Param1 = 50

[STATUS]
ID = 20
Group = 9
Name = 封咒
Param1 = *
Param2 = *

[STATUS]
ID = 21
Group = 10
Order = 1
Name = 一階重擊
Param2 = 30

[STATUS]
ID = 54
Group = 10
Order = 2
Name = 二階重擊
Param1 = 1
Param2 = 50

[STATUS]
ID = 53
Group = 10
Order = 2
Name = 二階重擊
Param1 = 2

[STATUS]
ID = 30
Group = 10
Order = 3
Name = 三階重擊
Param1 = 2
Param2 = 500

[STATUS]
ID = 31
Group = 10
Order = 4
Name = 四階重擊
Param1 = 3
Param2 = 150

[STATUS]
ID = 50
Group = 10
Order = 5
Name = 五階重擊
Param2 = 500

[STATUS]
ID = 32
Group = 17
Order = 1
Name = 淨心
Param1 = *
Param2 = *

[STATUS]
ID = 23
Group = 12
Name = 友善
Param1 = *
Param2 = *

[STATUS]
ID = 24
Group = 13
Order = 1
Name = 隱形
Param1 = *
Param2 = *

[STATUS]
ID = 25
Group = 13
Order = 2
Name = 隱遁
Param1 = *
Param2 = *

[STATUS]
ID = 26
Group = 14
Order = 1
Name = 照明
Param1 = *
Param2 = *

[STATUS]
ID = 27
Group = 11
Order = 1
Name = 崩潰
Param1 = *
Param2 = *

[STATUS]
ID = 22
Group = 11
Order = 2
Name = 混亂
Param1 = *
Param2 = *

[STATUS]
ID = 33
Group = 16
Name = 黑蝶
Param1 = *
Param2 = *

[STATUS]
ID = 34
Group = 18
Name = 詛咒
Param1 = *
Param2 = *

[STATUS]
ID = 35
Group = 19
Name = 替身
Param1 = *
Param2 = *

[STATUS]
ID = 38
Group = 21
Order = 4
Name = 戒運
Param1 = 8
Param2 = *

[STATUS]
ID = 43
Group = 21
Order = 2
Name = 仙運
Param1 = 3
Param2 = *

[STATUS]
ID = 47
Group = 25
Order = 2
Name = 經驗加倍
Param1 = 6
Param2 = *

[STATUS]
ID = 52
Group = 22
Order = 1
Name = 狂熱
Param1 = *
Param2 = *

[STATUS]
ID = 64
Name = 死亡

[STATUS]
ID = 65
Group = 21
Order = 1
Name = 靈運
Param1 = 2
Param2 = *

[STATUS]
ID = 66
Group = 27
Order = 1
Name = 鐵皮(獨立權位)
Param1 = -100
Param2 = -100

[STATUS]
ID = 67
Group = 5
Order = 1
Name = 鐵皮
Param1 = -3

[STATUS]
ID = 68
Group = 5
Order = 1
Name = 鐵皮
Param1 = -20
Param2 = -20

[STATUS]
ID = 69
Group = 26
Order = 1
Name = 洪鐘
Param1 = *
Param2 = *

[STATUS]
ID = 70
Group = 3
Order = 6
Name = 極速再生
Param1 = 3
Param2 = 5

[STATUS]
ID = 71
Group = 4
Order = 6
Name = 極速回精
Param1 = 3
Param2 = 4

[STATUS]
ID = 72
Group = 2
Order = 9
Name = 抗毒補血
Param1 = 5
Param2 = 2

[STATUS]
ID = 73
Group = 25
Order = 2
Name = 經驗加倍
Param1 = 9
Param2 = *

[STATUS]
ID = 74
Group = 23
Order = 2
Name = 鐵皮
Param1 = -35
Param2 = -45

[STATUS]
ID = 75
Group = 3
Order = 7
Name = 終極再生
Param1 = 1
Param2 = 75

[STATUS]
ID = 76
Group = 28
Order = 1
Name = 匯神
Param1 = 50

[STATUS]
ID = 77
Group = 29
Order = 1
Name = 免修裝
Param1 = *
Param2 = *

[STATUS]
ID = 78
Group = 6
Order = 1
Name = 活動勇猛
Param1 = 30

[STATUS]
ID = 79
Group = 21
Order = 4
Name = 天運
Param1 = 8
Param2 = *

[STATUS]
ID = 80
Group = 6
Order = 1
Name = 真勇猛
Param1 = 50

[STATUS]
ID = 81
Group = 4
Order = 4
Name = 超快速回精
Param1 = 1
Param2 = 75

[STATUS]
ID = 82
Group = 6
Order = 1
Name = 六年禮勇猛
Param1 = 20

[STATUS]
ID = 83
Group = 28
Order = 1
Name = 六年禮匯神
Param1 = 20

[STATUS]
ID = 84
Group = 5
Order = 1
Name = 鐵皮
Param1 = -35
Param2 = -35

[STATUS]
ID = 85
Group = 28
Order = 1
Name = 匯神
Param1 = 65
Param2 = 50

[STATUS]
ID = 86
Group = 6
Order = 2
Name = 勇猛
Param1 = 65
Param2 = 50

[STATUS]
ID = 87
Group = 23
Order = 2
Name = 鐵皮
Param1 = -96
Param2 = -96

[STATUS]
ID = 88
Group = 30
Order = 1
Name = 反傷
Param1 = 10
Param2 = 10

[STATUS]
ID = 89
Group = 28
Order = 1
Name = 匯神
Param1 = 25
Param2 = 20

[STATUS]
ID = 90
Group = 2
Order = 10
Name = 萬蠱噬魂
Param1 = 3
Param2 = -6

[STATUS]
ID = 91
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 12
Param2 = *

[STATUS]
ID = 92
Group = 23
Order = 2
Name = 鐵皮
Param1 = -95
Param2 = -95

[STATUS]
ID = 93
Group = 25
Order = 3
Name = 經驗加倍
Param2 = *

[STATUS]
ID = 94
Group = 21
Order = 8
Name = 咒運
Param2 = *

[STATUS]
ID = 95
Group = 30
Order = 2
Name = 反傷
Param1 = 50
Param2 = 50

[STATUS]
ID = 96
Group = 30
Order = 2
Name = 反傷
Param1 = 10

[STATUS]
ID = 97
Group = 30
Order = 2
Name = 反傷
Param2 = 10

[STATUS]
ID = 98
Group = 5
Order = 1
Name = 鐵皮
Param1 = -14

[STATUS]
ID = 99
Group = 5
Order = 1
Name = 鐵皮
Param2 = -14

[STATUS]
ID = 100
Group = 30
Order = 1
Name = 反傷
Param1 = 12
Param2 = 12

[STATUS]
ID = 101
Group = 25
Order = 2
Name = 經驗加倍
Param1 = 15
Param2 = *

[STATUS]
ID = 102
Group = 36
Order = 1
Name = 如意恢復
Param1 = 5
Param2 = 5

[STATUS]
ID = 103
Group = 38
Order = 1
Name = 七星連命
Param1 = 50

[STATUS]
ID = 104
Group = 39
Order = 1
Name = 鏡花水月
Param1 = 10100
Param2 = 45

[STATUS]
ID = 105
Group = 40
Order = 1
Name = 武器枷鎖
Param1 = 50
Param2 = 50

[STATUS]
ID = 106
Group = 31
Order = 1
Name = 不死身
Param1 = 60

[STATUS]
ID = 107
Group = 41
Order = 1
Name = 精力損耗
Param1 = -5
Param2 = 3

[STATUS]
ID = 108
Group = 42
Order = 1
Name = 精力抵血
Param1 = 30
Param2 = 5

[STATUS]
ID = 109
Group = 43
Order = 1
Name = 武器變緩

[STATUS]
ID = 110
Group = 37
Order = 1
Name = 回氣變緩
Param1 = 20

[STATUS]
ID = 112
Group = 28
Order = 1
Name = 匯神
Param1 = 70
Param2 = 60

[STATUS]
ID = 113
Group = 6
Order = 2
Name = 勇猛
Param1 = 70
Param2 = 55

[STATUS]
ID = 114
Group = 30
Order = 1
Name = 反傷
Param1 = 15
Param2 = 15

[STATUS]
ID = 115
Group = 5
Order = 1
Name = 鐵皮
Param1 = -40
Param2 = -40

[STATUS]
ID = 116
Group = 21
Order = 7
Name = 極大轉運
Param1 = 16
Param2 = *

[STATUS]
ID = 118
Group = 31
Order = 1
Name = 不死身
Param1 = 90

[STATUS]
ID = 119
Group = 5
Order = 2
Name = 鐵皮
Param1 = -30
Param2 = -30

[STATUS]
ID = 120
Group = 39
Order = 1
Name = 鏡花水月
Param2 = 35

[STATUS]
ID = 121
Group = 25
Order = 4
Name = 經驗加倍
Param1 = 15
Param2 = *

[STATUS]
ID = 122
Group = 21
Order = 5
Name = 真運
Param1 = 10
Param2 = *

[STATUS]
ID = 124
Group = 3
Order = 7
Name = 無敵再生
Param1 = 1
Param2 = 100

[STATUS]
ID = 125
Group = 4
Order = 4
Name = 無敵回精
Param1 = 1
Param2 = 100

[STATUS]
ID = 126
Group = 6
Order = 2
Name = 勇猛
Param2 = 30

[STATUS]
ID = 127
Group = 23
Order = 2
Name = 鐵皮
Param1 = -99
Param2 = -99

[STATUS]
ID = 128
Group = 44
Order = 4
Name = 覺醒加速
Param1 = 2
Param2 = *

[STATUS]
ID = 129
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 18
Param2 = *

[STATUS]
ID = 130
Group = 23
Order = 2
Name = 鐵皮
Param1 = -100
Param2 = -50

[STATUS]
ID = 131
Group = 23
Order = 2
Name = 鐵皮
Param1 = -50
Param2 = -100

[STATUS]
ID = 132
Group = 41
Order = 2
Name = 精力損耗
Param1 = -10
Param2 = 2

[STATUS]
ID = 133
Group = 41
Order = 3
Name = 精力損耗
Param1 = -100
Param2 = 2

[STATUS]
ID = 134
Group = 2
Order = 11
Name = 逆元咒神毒
Param1 = 3
Param2 = -15

[STATUS]
ID = 135
Group = 18
Name = 詛咒
Param1 = *
Param2 = *

[STATUS]
ID = 136
Group = 5
Order = 1
Name = 鐵皮
Param1 = -15
Param2 = -15

[STATUS]
ID = 137
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 24
Param2 = *

[STATUS]
ID = 138
Group = 30
Order = 2
Name = 反傷
Param1 = 90
Param2 = 90

[STATUS]
ID = 139
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 21
Param2 = *

[STATUS]
ID = 140
Group = 21
Order = 6
Name = 星運
Param1 = 12
Param2 = *

[STATUS]
ID = 141
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 27
Param2 = *

[STATUS]
ID = 142
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 30
Param2 = *

[STATUS]
ID = 143
Group = 3
Order = 8
Name = 超無敵再生
Param1 = 1
Param2 = 80

[STATUS]
ID = 144
Group = 4
Order = 7
Name = 超無敵回精
Param1 = 1
Param2 = 80

[STATUS]
ID = 145
Group = 5
Order = 1
Name = 鐵皮
Param1 = -45
Param2 = -45

[STATUS]
ID = 146
Group = 6
Order = 2
Name = 勇猛
Param1 = 75
Param2 = 60

[STATUS]
ID = 147
Group = 28
Order = 1
Name = 匯神
Param1 = 75
Param2 = 65

[STATUS]
ID = 148
Group = 30
Order = 1
Name = 反傷
Param1 = 20
Param2 = 20

[STATUS]
ID = 149
Group = 44
Order = 4
Name = 覺醒加速
Param1 = 3
Param2 = *

[STATUS]
ID = 150
Group = 7
Order = 4
Name = 新手玉珮
Param1 = 6
Param2 = 10

[STATUS]
ID = 151
Group = 4
Order = 4
Name = 快速回精
Param1 = 6
Param2 = 10

[STATUS]
ID = 152
Group = 5
Order = 3
Name = 鐵皮
Param1 = 50

[STATUS]
ID = 153
Group = 5
Order = 3
Name = 鐵皮
Param2 = 50

[STATUS]
ID = 154
Group = 2
Order = 12
Name = 大霹靂燃燒
Param1 = 2
Param2 = -200

[STATUS]
ID = 155
Group = 5
Order = 3
Name = 鐵皮
Param1 = 30
Param2 = 30

[STATUS]
ID = 156
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 33
Param2 = *

[STATUS]
ID = 157
Group = 21
Order = 7
Name = 大轉運
Param1 = 15
Param2 = *

[STATUS]
ID = 158
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 36
Param2 = *

[STATUS]
ID = 159
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 39
Param2 = *

[STATUS]
ID = 160
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 2
Param2 = *

[STATUS]
ID = 161
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 3
Param2 = *

[STATUS]
ID = 162
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 5
Param2 = *

[STATUS]
ID = 163
Group = 42
Order = 1
Name = 精力抵血
Param1 = 60
Param2 = 2

[STATUS]
ID = 164
Group = 3
Order = 8
Name = 超無敵再生
Param1 = 1
Param2 = 150

[STATUS]
ID = 165
Group = 4
Order = 7
Name = 超無敵回精
Param1 = 1
Param2 = 150

[STATUS]
ID = 166
Group = 3
Order = 8
Name = 真三無敵再生
Param1 = 1
Param2 = 2500

[STATUS]
ID = 167
Group = 4
Order = 7
Name = 真醍無敵回精
Param1 = 1
Param2 = 2500

[STATUS]
ID = 168
Group = 45
Order = 7
Name = 裝備破壞
Param1 = 50
Param2 = 50

[STATUS]
ID = 169
Group = 37
Order = 1
Name = 回氣加速
Param1 = 9

[STATUS]
ID = 170
Group = 45
Order = 7
Name = 裝備破壞
Param1 = 30
Param2 = 30

[STATUS]
ID = 171
Group = 36
Order = 1
Name = 如意恢復
Param1 = 200
Param2 = 200

[STATUS]
ID = 172
Group = 45
Order = 7
Name = 裝備破壞
Param1 = 10
Param2 = 10

[STATUS]
ID = 173
Group = 46
Name = 吸魔
Param1 = -90

[STATUS]
ID = 174
Group = 41
Order = 3
Name = 精力損耗
Param2 = 10

[STATUS]
ID = 175
Group = 40
Order = 1
Name = 武器枷鎖

[STATUS]
ID = 176
Group = 3
Order = 8
Name = 超無敵再生
Param1 = 1
Param2 = 200

[STATUS]
ID = 177
Group = 4
Order = 7
Name = 超無敵回精
Param1 = 1
Param2 = 200

[STATUS]
ID = 178
Group = 8
Order = 3
Name = 大敏銳
Param1 = 40

[STATUS]
ID = 179
Group = 25
Order = 3
Name = 經驗加倍
Param1 = 10
Param2 = *

[STATUS]
ID = 180
Group = 21
Order = 3
Name = 神運
Param1 = 5
Param2 = *

[STATUS]
ID = 181
Group = 23
Order = 1
Name = 鐵皮
Param1 = -10

[STATUS]
ID = 182
Group = 23
Order = 1
Name = 鐵皮
Param1 = -3

[STATUS]
ID = 183
Group = 23
Order = 1
Name = 鐵皮
Param1 = -20
Param2 = -20

[STATUS]
ID = 184
Group = 23
Order = 1
Name = 鐵皮
Param1 = -14

[STATUS]
ID = 185
Group = 23
Order = 1
Name = 鐵皮
Param2 = -14

[STATUS]
ID = 186
Group = 23
Order = 1
Name = 鐵皮
Param1 = -10
Param2 = -10

[STATUS]
ID = 187
Group = 23
Order = 1
Name = 鐵皮
Param1 = -15
Param2 = -15

[STATUS]
ID = 188
Group = 47
Order = 1
Name = 省精
Param1 = 50

[STATUS]
ID = 189
Group = 48
Order = 1
Name = 早氣
Param1 = 30
Param2 = 50

[STATUS]
ID = 190
Group = 1
Order = 1
Name = 強疾行
Param1 = 10
Param2 = 6

[STATUS]
ID = 191
Group = 1
Order = 1
Name = 真疾行
Param1 = 10
Param2 = 7

[STATUS]
ID = 192
Group = 1
Order = 6
Name = 超疾行
Param1 = 10
Param2 = 8

[STATUS]
ID = 193
Group = 1
Order = 6
Name = 神疾行
Param1 = 10
Param2 = 9

[STATUS]
ID = 194
Group = 49
Order = 1
Name = 連擊
Param1 = 20
Param2 = 1

[STATUS]
ID = 195
Group = 49
Order = 1
Name = 連擊
Param1 = 5
Param2 = 1

[STATUS]
ID = 196
Group = 50
Order = 1
Name = 抗暈

[STATUS]
ID = 197
Group = 52
Order = 1
Name = 準備受難
Param2 = 198

[STATUS]
ID = 198
Group = 1
Order = 254
Name = 持旗debff
Param1 = -30
Param2 = 1

[STATUS]
ID = 199
Group = 45
Order = 7
Name = 裝備破壞
Param1 = 5
Param2 = 25

[STATUS]
ID = 200
Name = 升級

[STATUS]
ID = 201
Name = 受傷

[STATUS]
ID = 202
Name = 死亡

[STATUS]
ID = 203
Name = 求婚

[STATUS]
ID = 204
Group = 43
Order = 1
Name = 武器變緩
Param1 = 6


