const SLOT_KEY='szo_v101_support_slots';
function $(id){return document.getElementById(id)}
function n(v){return Number(v||0)}
function fmt(v){return Math.round(Number(v||0)).toLocaleString()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getSlots(){try{return JSON.parse(localStorage.getItem(SLOT_KEY)||'{}')}catch(e){return {}}}
function setSlots(v){localStorage.setItem(SLOT_KEY,JSON.stringify(v))}
function starNeed(data,a,b){const t=data.starRequirements||{};let sum=0;for(let i=n(a)+1;i<=n(b);i++)sum+=n(t[i]?.single);return sum}
function auraNeed(data,a,b){const t=data.auraTable||{};let sum=0;for(let i=n(a)+1;i<=n(b);i++)sum+=n(t[i]?.single);return sum}
function ability(data,name,star){const base=data.baseStats?.[name]||{};const mult=data.starMultipliers||{};const out={};for(const st of data.stats||[])out[st]=n(base[st])*n(mult[st]?.[star]??1);return out}
function addStats(a,b,rate=1){const o={...a};for(const k in b)o[k]=n(o[k])+n(b[k])*rate;return o}
function renderStats(obj){return `<div class="modGrid">${Object.entries(obj).map(([k,v])=>`<div class="statLine"><b>${esc(k)}</b><span>${fmt(v)}</span></div>`).join('')}</div>`}
function namesOptions(data){return (data.displayNames||Object.keys(data.baseStats||{})).filter(x=>data.baseStats?.[x]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function readPlan(){return Array.from({length:5},(_,i)=>({name:$('jsName'+i)?.value||'',star:n($('jsStar'+i)?.value)}))}
function calcPlan(data,plan){let total={};plan.forEach((p,i)=>{if(!p.name)return;total=addStats(total,ability(data,p.name,p.star),i===0?1:0.1)});return total}
function planSummary(plan){return plan.filter(p=>p.name).map(p=>`${p.name}(${p.star})`).join('、')||'空白'}
function planInputs(data){let opt=namesOptions(data);return Array.from({length:5},(_,i)=>`<div class="slotBox"><b>${i===0?'主降神':'副降神'+i}</b><div class="modRow"><select id="jsName${i}"><option value="">未選擇</option>${opt}</select><input id="jsStar${i}" type="number" min="0" max="20" value="${i===0?10:1}"></div></div>`).join('')}
function supportPage(data){reader.innerHTML=`<div class="card"><h1>副降神試算</h1>${planInputs(data)}<div class="saveBtns"><button id="directCalc">直接試算</button>${['A','B','C','D','E'].map(s=>`<button data-save="${s}">存檔${s}</button>`).join('')}</div><div id="supportResult" class="card" style="margin-top:12px"></div></div>`; $('directCalc').onclick=()=>{$('supportResult').innerHTML='<h2>試算結果</h2>'+renderStats(calcPlan(data,readPlan()))};document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const slots=getSlots();slots[b.dataset.save]=readPlan();setSlots(slots);$('supportResult').innerHTML=`<div class="notice">已存檔 ${b.dataset.save}：${esc(planSummary(slots[b.dataset.save]))}</div>`})}
function comparePage(data){const slots=getSlots();reader.innerHTML=`<div class="card"><h1>副降神存檔比較</h1><div class="modGrid">${[0,1,2,3,4].map(i=>`<div><label>比較欄 ${i+1}</label><select id="cmp${i}"><option value="">不顯示</option>${['A','B','C','D','E'].map(s=>`<option value="${s}">${s}｜${esc(planSummary(slots[s]||[]))}</option>`).join('')}</select></div>`).join('')}</div><button class="primary" id="doCmp" style="margin-top:12px">開始比較</button><div id="cmpOut" style="margin-top:12px"></div></div>`;$('doCmp').onclick=()=>{const picks=[0,1,2,3,4].map(i=>$('cmp'+i).value).filter(Boolean);$('cmpOut').innerHTML=`<div class="modGrid">${picks.map(s=>`<div class="card"><h2>存檔 ${s}</h2><div class="muted">${esc(planSummary(slots[s]||[]))}</div>${renderStats(calcPlan(data,slots[s]||[]))}</div>`).join('')}</div>`}}
function starAuraPage(data){reader.innerHTML=`<div class="card"><h1>星等 / 靈氣計算</h1><div class="pageTabs"><button class="pageTab active" id="tabStar">星等計算</button><button class="pageTab" id="tabAura">靈氣計算</button></div><div id="saBody"></div></div>`;const body=$('saBody');function star(){body.innerHTML=`<div class="modRow"><input id="from" type="number" min="0" max="20" value="0"><input id="to" type="number" min="0" max="20" value="3"></div><button class="primary" id="calc">計算</button><div id="out" class="notice"></div>`;$('calc').onclick=()=>{$('out').textContent=`需要降神：${fmt(starNeed(data,$('from').value,$('to').value))} 顆`}}function aura(){body.innerHTML=`<div class="modRow"><input id="from" type="number" min="1" value="1"><input id="to" type="number" min="1" value="20"></div><button class="primary" id="calc">計算</button><div id="out" class="notice"></div>`;$('calc').onclick=()=>{$('out').textContent=`需要靈氣：${fmt(auraNeed(data,$('from').value,$('to').value))}`}}$('tabStar').onclick=star;$('tabAura').onclick=aura;star()}
function expPage(data){reader.innerHTML=`<div class="card"><h1>等級 / 經驗丹</h1><div class="muted">經驗表已保留在 jiangshen.json。這裡先提供經驗丹換算。</div><div class="modRow"><input id="expNeed" type="number" value="3000000000000"><select id="pill"><option value="800000000000">乙太 8000億</option><option value="300000000000">鑽石 3000億</option><option value="50000000000">真元 500億</option></select></div><button class="primary" id="calc">計算</button><div id="out" class="notice"></div></div>`;$('calc').onclick=()=>{$('out').textContent=`約需要 ${Math.ceil(n($('expNeed').value)/n($('pill').value)).toLocaleString()} 顆`}}
function starsPage(data){reader.innerHTML=`<div class="card"><h1>20星等表</h1><div class="tableWrap"><table><tr><th>星等</th><th>單階需求</th><th>累計</th></tr>${Object.entries(data.starRequirements||{}).map(([k,v])=>`<tr><td>${k}</td><td>${fmt(v.single)}</td><td>${fmt(v.cum)}</td></tr>`).join('')}</table></div></div>`}
function menu(data){reader.innerHTML=`<div class="card"><h1>降神、經驗、修練試算</h1><div class="quick"><button id="mSupport">副降神試算<small>五格、存檔 A-E</small></button><button id="mCompare">副降神比較<small>載入存檔比較</small></button><button id="mStars">20星等<small>星等需求表</small></button><button id="mStarAura">星等 / 靈氣<small>兩個按鈕頁面</small></button><button id="mExp">等級 / 經驗丹<small>經驗丹估算</small></button></div></div>`;$('mSupport').onclick=()=>supportPage(data);$('mCompare').onclick=()=>comparePage(data);$('mStars').onclick=()=>starsPage(data);$('mStarAura').onclick=()=>starAuraPage(data);$('mExp').onclick=()=>expPage(data)}
export async function initJiangshen({reader:rd,loadJson}){window.reader=rd;const data=await loadJson('data/jiangshen.json',{});menu(data)}